using System.Text;
using SecondKey.Standards.Generator.Model;

namespace SecondKey.Standards.Generator.Generation;

/// <summary>
/// Emits the gate's configuration: one <c>dotnet_diagnostic.&lt;id&gt;.severity</c> line per
/// diagnostic a rule maps to, at the rule's severity — as an <c>.editorconfig</c> scoped to the
/// rule's file patterns, and as a global analyzer config for the NuGet package.
/// </summary>
internal static class AnalyzerConfigEmitter
{
    /// <summary>
    /// The global config's precedence. The .NET SDK's own analysis-level configs use negative
    /// levels; a repository's own <c>.globalconfig</c> defaults to 100; any <c>.editorconfig</c>
    /// entry wins over every global config. 0 sits between, so a consumer can always override.
    /// </summary>
    public const int GlobalLevel = 0;

    public static void Emit(GeneratedTree tree, string version, IReadOnlyList<Rule> rules)
    {
        tree.Add(GeneratedPaths.EditorConfig, EditorConfig(version, rules));
        tree.Add(GeneratedPaths.GlobalConfig, GlobalConfig(version, rules));
    }

    private static string EditorConfig(string version, IReadOnlyList<Rule> rules)
    {
        var builder = new StringBuilder();
        Header(builder, version);
        builder.Append("#\n");
        builder.Append("# Merge these sections into a repository's own .editorconfig, or use the global config in\n");
        builder.Append("# the SecondKey.Standards package instead. Each section is scoped to the files the rule\n");
        builder.Append("# applies to (its appliesTo), and .editorconfig entries take precedence over any global\n");
        builder.Append("# analyzer config.\n");

        var mapped = rules.Where(rule => rule.Diagnostics.Count > 0).ToList();
        var patterns = mapped.SelectMany(rule => rule.AppliesTo).Distinct(StringComparer.Ordinal);
        foreach (var pattern in patterns)
        {
            builder.Append('\n').Append('[').Append(pattern).Append("]\n");
            foreach (var rule in mapped.Where(rule => rule.AppliesTo.Contains(pattern, StringComparer.Ordinal)))
            {
                Lines(builder, rule);
            }
        }

        return builder.ToString();
    }

    private static string GlobalConfig(string version, IReadOnlyList<Rule> rules)
    {
        var builder = new StringBuilder();
        Header(builder, version);
        builder.Append("#\n");
        builder.Append("# A global analyzer config: it applies to every file of every project that loads it. The\n");
        builder.Append("# SecondKey.Standards NuGet package loads it through build/SecondKey.Standards.props;\n");
        builder.Append("# without the package, copy it to a repository root as .globalconfig.\n");
        builder.Append("#\n");
        builder.Append("# global_level 0 places it above the .NET SDK's analysis-level defaults (negative levels)\n");
        builder.Append("# and below a repository's own .globalconfig (100 unless set); any .editorconfig entry\n");
        builder.Append("# overrides it. A consumer can always tune a severity locally.\n");
        builder.Append("is_global = true\n");
        builder.Append("global_level = ").Append(GlobalLevel.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append('\n');

        foreach (var rule in rules.Where(rule => rule.Diagnostics.Count > 0))
        {
            builder.Append('\n');
            Lines(builder, rule);
        }

        return builder.ToString();
    }

    private static void Header(StringBuilder builder, string version)
    {
        builder.Append("# Second Key migration standards ").Append(version)
            .Append(": the severity of every diagnostic that checks a standard.\n");
        builder.Append("# Generated by secondkey-standards from standards/*.md. Do not edit: change the rule and\n");
        builder.Append("# regenerate.\n");
    }

    private static void Lines(StringBuilder builder, Rule rule)
    {
        builder.Append("# ").Append(rule.Id).Append(' ').Append(rule.Title).Append('\n');
        foreach (var diagnostic in rule.Diagnostics)
        {
            builder.Append("dotnet_diagnostic.").Append(diagnostic).Append(".severity = ").Append(rule.Severity.ToName()).Append('\n');
        }
    }
}
