using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using SecondKey.Standards.Generator.Model;
using SecondKey.Standards.Generator.Parsing;

namespace SecondKey.Standards.Generator.Generation;

/// <summary>
/// <c>generated/manifest.json</c>: the machine-readable index of one standards version — its
/// version, a digest of everything the generator produced for it, and every rule with its own
/// digest. The version gate reads the committed one to see whether content moved; the drift check
/// reads two of them (a consumer's pinned version and the latest) to say which rules changed.
/// </summary>
public sealed record Manifest
{
    [JsonPropertyName("$comment")]
    public string? Comment { get; init; }

    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    [JsonPropertyName("version")]
    public string Version { get; init; } = "";

    /// <summary>
    /// A digest of every generated file except this one, computed with the version replaced by a
    /// fixed value, so it changes when content changes and only then.
    /// </summary>
    [JsonPropertyName("contentHash")]
    public string ContentHash { get; init; } = "";

    [JsonPropertyName("skill")]
    public string Skill { get; init; } = "";

    [JsonPropertyName("package")]
    public string Package { get; init; } = "";

    [JsonPropertyName("rules")]
    public IReadOnlyList<ManifestRule> Rules { get; init; } = [];

    internal static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = true,
        IndentSize = 2,
        DefaultIgnoreCondition = JsonIgnoreCondition.Never,
        // The file is read by programs and by people in a diff, never embedded in HTML, so titles
        // keep their characters ("—") instead of \u escapes.
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    public static Manifest Create(PackConfig pack, string version, string contentHash, IReadOnlyList<Rule> rules) => new()
    {
        Comment = "Generated by secondkey-standards: the index of one standards version. Do not edit.",
        Name = pack.Name,
        Version = version,
        ContentHash = contentHash,
        Skill = pack.Skill.Name,
        Package = pack.Package.Id,
        Rules = rules.Select(rule => new ManifestRule
        {
            Id = rule.Id,
            Title = rule.Title,
            Severity = rule.Severity.ToName(),
            Category = rule.Category,
            Diagnostics = rule.Diagnostics,
            Principle = rule.Principle,
            Hash = RuleHash(rule),
        }).ToList(),
    };

    public string ToJson() => JsonSerializer.Serialize(this, SerializerOptions) + "\n";

    /// <summary>Parses a manifest; returns null when the text is not one.</summary>
    public static Manifest? TryParse(string json)
    {
        try
        {
            var manifest = JsonSerializer.Deserialize<Manifest>(json, SerializerOptions);
            return manifest is { Version.Length: > 0 } ? manifest : null;
        }
        catch (JsonException)
        {
            return null;
        }
    }

    /// <summary>A rule's digest: its source file as the parser saw it, so any edit to the rule changes it.</summary>
    private static string RuleHash(Rule rule)
    {
        var text = $"{rule.Id}\n{rule.Title}\n{rule.Severity.ToName()}\n{rule.Category}\n"
            + $"{string.Join(',', rule.AppliesTo)}\n{string.Join(',', rule.Diagnostics)}\n{rule.Principle}\n{rule.Body}";
        return Digest(text);
    }

    internal static string Digest(string text) =>
        "sha256:" + Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(text)))[..16];
}

public sealed record ManifestRule
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = "";

    [JsonPropertyName("title")]
    public string Title { get; init; } = "";

    [JsonPropertyName("severity")]
    public string Severity { get; init; } = "";

    [JsonPropertyName("category")]
    public string Category { get; init; } = "";

    [JsonPropertyName("diagnostics")]
    public IReadOnlyList<string> Diagnostics { get; init; } = [];

    [JsonPropertyName("principle")]
    public string? Principle { get; init; }

    [JsonPropertyName("hash")]
    public string Hash { get; init; } = "";
}

internal static class ContentHash
{
    /// <summary>
    /// The version the content is rendered with for hashing. Generated files mention the version
    /// (the package's &lt;Version&gt;, the skill's metadata), so hashing them as written would make
    /// every version bump look like a content change.
    /// </summary>
    public const string SentinelVersion = "0.0.0";

    public static string Compute(GeneratedTree tree)
    {
        var builder = new StringBuilder();
        foreach (var (path, contents) in tree.Files)
        {
            builder.Append(path).Append('\0').Append(contents).Append('\0');
        }

        return Manifest.Digest(builder.ToString());
    }
}
