using System.Globalization;
using System.Security;
using System.Text;
using SecondKey.Standards.Generator.Model;

namespace SecondKey.Standards.Generator.Generation;

/// <summary>
/// Emits the NuGet package project that delivers the global analyzer config to consuming builds.
/// The package carries no assembly: its <c>build/&lt;id&gt;.props</c> adds the config to the
/// compiler's <c>EditorConfigFiles</c>, the same item the .NET SDK uses for its own analysis-level
/// configs, so a consumer gets the severities by adding one package reference.
/// </summary>
internal static class PackageEmitter
{
    /// <summary>The name the global config is packed under, next to the props that load it.</summary>
    public static string PackedGlobalConfigName(PackageConfig package) => $"{package.Id}.globalconfig";

    /// <summary>Set to <c>false</c> in a consuming project to switch the package's configuration off.</summary>
    public const string OptOutProperty = "SecondKeyStandardsGlobalConfig";

    /// <summary>The MSBuild property that tells a consuming build which standards version it has.</summary>
    public const string VersionProperty = "SecondKeyStandardsVersion";

    public static void Emit(GeneratedTree tree, PackConfig pack, string version, IReadOnlyList<Rule> rules)
    {
        tree.Add(GeneratedPaths.PackageProject(pack.Package.Id), Project(pack, version));
        tree.Add(GeneratedPaths.PackageProps(pack.Package.Id), Props(pack.Package, version));
        tree.Add(GeneratedPaths.PackageReadme, Readme(pack, version, rules));
    }

    private static string Project(PackConfig pack, string version)
    {
        var package = pack.Package;
        var xml = new StringBuilder();
        xml.Append("<Project Sdk=\"Microsoft.NET.Sdk\">\n\n");
        xml.Append("  <!--\n");
        xml.Append("    Generated by secondkey-standards from catalog/pack.json. Do not edit.\n\n");
        xml.Append("    A configuration-only package: no assembly (IncludeBuildOutput=false), a development\n");
        xml.Append("    dependency (so it never flows into a consumer's runtime dependencies), and build/ props\n");
        xml.Append("    that load the global analyzer config. Pack it with:\n");
        xml.Append("      dotnet pack ").Append(GeneratedPaths.PackageProject(package.Id)).Append(" -o artifacts/packages\n");
        xml.Append("  -->\n");
        xml.Append("  <PropertyGroup>\n");
        xml.Append("    <TargetFramework>netstandard2.0</TargetFramework>\n");
        xml.Append("    <PackageId>").Append(Escape(package.Id)).Append("</PackageId>\n");
        xml.Append("    <Version>").Append(Escape(version)).Append("</Version>\n");
        xml.Append("    <Description>").Append(Escape(package.Description)).Append("</Description>\n");
        xml.Append("    <PackageTags>secondkey;standards;migration;analyzers;globalconfig;editorconfig</PackageTags>\n");
        xml.Append("    <PackageProjectUrl>").Append(Escape(pack.Repository)).Append("</PackageProjectUrl>\n");
        xml.Append("    <PackageReadmeFile>README.md</PackageReadmeFile>\n");
        xml.Append("    <PackageLicenseFile>LICENSE</PackageLicenseFile>\n");
        xml.Append("    <IncludeBuildOutput>false</IncludeBuildOutput>\n");
        xml.Append("    <DevelopmentDependency>true</DevelopmentDependency>\n");
        xml.Append("    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>\n");
        xml.Append("    <!-- The global config's source is a dotfile, which NuGet excludes unless told otherwise. -->\n");
        xml.Append("    <NoDefaultExcludes>true</NoDefaultExcludes>\n");
        xml.Append("    <IsPackable>true</IsPackable>\n");
        xml.Append("  </PropertyGroup>\n\n");
        xml.Append("  <ItemGroup>\n");
        xml.Append("    <None Include=\"build/").Append(package.Id).Append(".props\" Pack=\"true\" PackagePath=\"build/")
            .Append(package.Id).Append(".props\" />\n");
        xml.Append("    <None Include=\"../config/.globalconfig\" Pack=\"true\" PackagePath=\"build/")
            .Append(PackedGlobalConfigName(package)).Append("\" />\n");
        xml.Append("    <None Include=\"README.md\" Pack=\"true\" PackagePath=\"README.md\" />\n");
        xml.Append("    <None Include=\"../../LICENSE\" Pack=\"true\" PackagePath=\"\" />\n");
        xml.Append("  </ItemGroup>\n\n");
        xml.Append("</Project>\n");
        return xml.ToString();
    }

    private static string Props(PackageConfig package, string version)
    {
        var xml = new StringBuilder();
        xml.Append("<Project>\n\n");
        xml.Append("  <!--\n");
        xml.Append("    Generated by secondkey-standards. Do not edit.\n\n");
        xml.Append("    Adds the Second Key standards' global analyzer config to this project's compilation.\n");
        xml.Append("    Set ").Append(OptOutProperty).Append(" to false to switch it off; override a single\n");
        xml.Append("    severity in the repository's .editorconfig, which always takes precedence.\n");
        xml.Append("  -->\n");
        xml.Append("  <PropertyGroup>\n");
        xml.Append("    <").Append(VersionProperty).Append('>').Append(Escape(version)).Append("</").Append(VersionProperty).Append(">\n");
        xml.Append("  </PropertyGroup>\n\n");
        xml.Append("  <ItemGroup Condition=\"'$(").Append(OptOutProperty).Append(")' != 'false'\">\n");
        xml.Append("    <EditorConfigFiles Include=\"$(MSBuildThisFileDirectory)").Append(PackedGlobalConfigName(package)).Append("\" />\n");
        xml.Append("  </ItemGroup>\n\n");
        xml.Append("</Project>\n");
        return xml.ToString();
    }

    private static string Readme(PackConfig pack, string version, IReadOnlyList<Rule> rules)
    {
        var package = pack.Package;
        var builder = new StringBuilder();
        builder.Append("# ").Append(package.Id).Append("\n\n");
        builder.Append(package.Description).Append("\n\n");
        builder.Append("Second Key standards version ").Append(version).Append(". The rules themselves, and the skill that ")
            .Append("tells the migration agent about them, are in ").Append(CultureInfo.InvariantCulture, $"<{pack.Repository}>").Append(".\n\n");
        builder.Append("## Install\n\n");
        builder.Append("With central package management, in `Directory.Packages.props`:\n\n");
        builder.Append("```xml\n<GlobalPackageReference Include=\"").Append(package.Id).Append("\" Version=\"").Append(version).Append("\" />\n```\n\n");
        builder.Append("Or in each project (or a `Directory.Build.props`):\n\n");
        builder.Append("```xml\n<PackageReference Include=\"").Append(package.Id).Append("\" Version=\"").Append(version)
            .Append("\" PrivateAssets=\"all\" />\n```\n\n");
        builder.Append("The diagnostics are reported by the analyzers that own them: Portcullis for the `PORTCULLIS_` ids, ")
            .Append("the .NET SDK for the `CA` ids. This package sets their severity; it does not add analyzers.\n\n");
        builder.Append("## Severities\n\n");
        builder.Append(MarkdownText.Table(
            ["Diagnostic", "Severity", "Standard"],
            rules.SelectMany(rule => rule.Diagnostics.Select(diagnostic => (IReadOnlyList<string>)
            [
                MarkdownText.Code(diagnostic),
                rule.Severity.ToName(),
                $"{rule.Id} {rule.Title}",
            ])))).Append("\n\n");
        builder.Append("## Overriding\n\n");
        builder.Append("An entry in the repository's `.editorconfig` always wins:\n\n");
        builder.Append("```ini\n[*.cs]\ndotnet_diagnostic.CA1305.severity = suggestion\n```\n\n");
        builder.Append("Set `<").Append(OptOutProperty).Append(">false</").Append(OptOutProperty)
            .Append(">` in a project to switch the package's configuration off there.\n");
        return builder.ToString();
    }

    private static string Escape(string value) => SecurityElement.Escape(value);
}
